sudo: false

language: php

cache: apt

addons:
  apt:
    packages:
    - libsaxonb-java
    - gnuplot
    - default-jre
    - libcurl3
    - basex

script: php compile.php -V

notifications:
  email:
    recipients:
      - lucas.gautheron@gmail.com
    on_success: change # default: change
    on_failure: always

