sudo: required

language: php

cache: apt

before_install:
- sudo apt-get update -qq libsaxonb-java gnuplot default-jre libcurl3 basex

script: php compile.php -V

notifications:
  email:
    recipients:
      - lucas.gautheron@gmail.com
    on_success: change # default: change
    on_failure: always

