sudo: false
dist: trusty
language: php
cache: apt

addons:
  apt:
    packages:
    - libsaxonb-java
    - gnuplot
    - build-essential
    - gfortran
    - default-jre
    - libcurl3

install:
    - wget http://files.basex.org/releases/8.6.1/BaseX861.zip && unzip BaseX861.zip
    - export PATH=$PWD/basex/bin:$PATH

script: make deploy

notifications:
  email:
    recipients:
      - lucas.gautheron@gmail.com
    on_success: change # default: change
    on_failure: always

